### ISSUE TITLE
As an event organiser, I want to manage my organisation. 

### ISSUE THREAD

**Issue by pabloVoorvaart** [streamethorg/streameth-platform#381]
## User Story
As an event organiser, I want to manage my organisation using /studio. Ideally, I want to: 

- Modify my organisation information
- Invite users to co-manage the organisation
- Delete my organisation. 

## Tasks Breakdown (Optional)
- [ ] Task 1 (e.g., setup the database schema)
- [ ] Task 2 (e.g., implement the API endpoint)
- [ ] Task 3 (e.g., create the UI component)
