### ISSUE TITLE
As a User, I want to have subtitles in my videos and clips.

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#633]
## User Story
**As a** User, **I want** to have subtitles in my videos and clips, **so that** I don't have to take my videos to other apps to add subtitles.

## Acceptance Criteria
-  [ ] Given a video file is uploaded, when it's processed, then subtitles are automatically generated and added to the video.
-  [ ] Given an option to edit subtitles, when the user edits, then the changes are saved and reflected in the video.
-  [ ] Given a toggle or checkbox, when the user interacts with it in the editing view, then the user can choose to add or remove subtitles from the video.

## Non-functional Criteria (if applicable)
N/A

## Dependencies (if any)
-  [ ] Requires Livepeer AI service to be available and integrated.

## Notes
-  Livepeer AI Audio to text service will be utilized to generate subtitles.
-  Provide users with the ability to upload subtitle files (e.g., SRT) if they prefer manual uploads.
- The flow should be as follows:

1. Clip gets created
2. Once processed by Livepeer, server downloads the clip
3. Server make API request to Livepeer AI
4. Server receives response
5. Server adds response to video metadata using FFMPEG
6. User now sees a video with the option to toggle on or off subtitles

## Tasks Breakdown 
-  [ ] Integrate Livepeer AI service for subtitle generation.
-  [ ] Implement backend logic to process uploaded videos and add subtitles (perhaps new API endpoints).
-  [ ] Frontend to show full trancript.
-  [ ] Downloaded videos with FFMPEG in a `temp/` folder to be deleted when processed.
