### ISSUE TITLE
As a User, I want to upload videos and clips to different social media

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#634]
## User Story
**As a** User, **I want** a simple button for each social media platform in each video or clip view, **so that** I can quickly and easily upload my streams and clips to different social media platforms like YouTube, X, and so on.

## Acceptance Criteria
- [ ] Given a video or clip view, when the social media button for YouTube is clicked, then the content is automatically uploaded to my YouTube account.
- [ ] Given a video or clip view, when the social media button for X is clicked, then the content is automatically uploaded to my X account.
- [ ] Given a video or clip view with multiple social media buttons, when a button is clicked, then the respective social media platform confirms the upload was successful with a notification or message.

## Non-functional Criteria
- [ ] Documentation for each third party API must be done. It should explain briefly how the integration was developed.

## Dependencies (if any)
- [x] OAuth authentication must be implemented with each social media platform to authorize uploads.
- [x] Modify Organization model to include an array of social connections.

## Notes
- The upload buttons should include user feedback for both successful and failed uploads, such as loading spinners, progress bars or red and green indicators for failed and success, to indicate the upload status.
- The auth flow should be triggered from the frontend.
- The /publish endpoint should trigger the refresh token mechanism.

## Tasks Breakdown
- [ ] Implement OAuth authentication for YouTube and X.
- [x] Integrate YouTube API for content upload.
- [ ] Integrate X API for content upload.
- [ ] Develop frontend interface for upload buttons and status notifications.
