### ISSUE TITLE
As a User, I want to explore all covered events by StreamETH

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#641]
## User Story
As a User, I want to explore all covered events by StreamETH so that I can discover the work that streameth is able to do.

## Acceptance Criteria
- [ ] Given I am on the streameth.org/explore, when I click on an topic tab I should only see sessions that have the selected topic
- [ ] Given I am viewing the events list, when I click on an session card, then I should be taken to the video page
- [ ] Given I am on the events listing page, when I use filter or search options, then the list should update to show relevant events based on my criteria.

## Non-functional Criteria (if applicable)
- [ ] The UI should be responsive and work well on both desktop and mobile devices.

## Dependencies (if any)
- [ ] Fix search bar component
- [ ] Fix video redirects

## Notes (Optional)
- Consider implementing infinite scroll.
- Data fetching for featured events should be done in the server

## Mockups & Examples (Optional)
![CleanShot 2024-08-02 at 19 35 21](https://github.com/user-attachments/assets/4f9e4d9c-9c78-4df1-967b-0665daf546f3)

![CleanShot 2024-08-02 at 19 35 27](https://github.com/user-attachments/assets/595f5955-b2f4-4abd-abb4-ee30ca0312fa)

## Tasks Breakdown (Optional)
- [ ] Design the events listing page layout
- [ ] Develop the events listing page with grid/list view
- [ ] Implement filtering and search functionality
- [ ] Add infinite scroll feature
