### ISSUE TITLE
As a User, I want to be able to start a livestream on X.

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#732]
## User Story
As a User, I want to be able to start a livestream on X (formerly Twitter), so that I can engage with my followers in real-time.

## Acceptance Criteria
- [ ] Given I'm logged in and have linked my X account, when I click "Start Livestream", then I can select X as the streaming platform.
- [ ] After ending the stream, the video should be available on my X profile for replay.

## Dependencies
- [ ] X API integration for livestreaming must be completed.
- [ ] OAuth authentication with X must be implemented.

## Tasks Breakdown
- [ ] Implement X API integration for livestreaming.
- [ ] Develop UI for X-specific streaming destination (buttons, modals, etc...)
- [ ] Ensure stream archiving on X profile after completion.

## Notes
- It would be nice to make notes on what parts of the API are from X V1.0 API and V2.0

**Comment by Eric-Vondee** [comment]
This feature is currently unavailable due to limited access to Twitter's media API
