### ISSUE TITLE
As a User, I want to upload multiple videos simultaneously

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#868]
## User Story
**As a** User, **I want** to be able to upload multiple videos in parallel, **so that** I can efficiently manage multiple video uploads without needing to open several tabs.

## Acceptance Criteria
- [ ] Given I'm on the video upload page, when I select multiple video files, then the system should initiate parallel uploads for all selected videos.
- [ ] Given I've initiated multiple video uploads, when a single video upload is complete, then the system should display a "Processing" state for that video.
- [ ] Given I've initiated multiple video uploads, when I click on a video in the upload queue, then a modal should appear allowing me to edit that video's metadata (title, description, etc.).
- [ ] Given I'm uploading multiple videos, when viewing the upload interface, then I should see a compact representation of uploading videos in the corner of the screen, similar to YouTube's approach.

## Non-functional Criteria
- [ ] The system should handle at least 5 simultaneous video uploads without significant performance degradation.

## Notes
- The current technical limitations prevent showing exact upload progress percentages. We'll use a more general progress indicator (e.g., "Uploading", "Processing") instead.
- This feature aims to mimic YouTube's approach to multiple video uploads, as shown in the provided mockups.

## Mockups & Examples
YouTube's approach:
<img width="945" alt="Screenshot 2024-08-15 at 09 20 39" src="https://github.com/user-attachments/assets/5898012f-c329-4833-bf9b-3f47b7a9fdd2">
<img width="529" alt="Screenshot 2024-08-15 at 09 20 50" src="https://github.com/user-attachments/assets/6da30a8c-6df8-412c-84fe-b94a170ac094">

## Tasks Breakdown
- [ ] Update the frontend UI to allow multiple file selection
- [ ] Implement parallel upload functionality in the frontend (NextJS)
- [ ] Create a compact upload queue display component
- [ ] Develop a modal for editing individual video metadata
- [ ] Implement video processing status updates from backend to frontend
- [ ] Fix the issue with thumbnail not uploading during video upload
- [ ] Conduct thorough testing of the parallel upload feature
