### ISSUE TITLE
As a QA Engineer, I would like to test the features of the `/studio` page

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#908]
## User Story
**As a** Developer, **I want** to test the features of `/studio`, **so that** it is easy to detect errors while programming.

## Acceptance Criteria
- [ ] The `/studio/{organizationPage}` should be thoroughly tested
- [ ] The `/studio/{organizationPage}/livestreams/{stageID}` features should be tested

## Non-functional Criteria (if applicable)
- [ ] Add additional information on Notion, like the tests that I make
- [ ] Make sure to do 'failure' testing
- [ ] Github Actions should work

## Tasks Breakdown (Optional)
- [ ] Write down the test scenarios on Notion
- [ ] Progam tests for `/studio/{organizationPage}`
- [ ] Program tests for `/studio/{organizationPage}/livestreams/{stageID}`
