### ISSUE TITLE
As a User, I want to create reel style videos

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#914]
## User Story
**As a** User, **I want** to download reel style videos, **so that** I can easily share vertical format content.

## Acceptance Criteria
- [ ] Given a clip, when I click on `Edit` button, then I should get redirected to the editing app
- [ ] Given a clip inside the editing app, when I click on video aspect ratio 9:16 button, I should see the preview of the video that I will get
- [ ] Given a resized clip inside the editing app, when I click on download, I should get the 9:16 video downloaded

## Non-functional Criteria (if applicable)
- [ ] This should provide a simple and seamless experience for getting vertical content
- [ ] We should not depend on Livepeer studio

## Dependencies (if any)
- [ ] Requires a first implementation of video editing capabillities (#915)

## Mockups & Examples (Optional)

See [veed.io](https://www.veed.io/) for reference on how to do the video resize

## Tasks Breakdown (Optional)
- [ ] Add vertical video editing capabilities to the _editing app_
