### ISSUE TITLE
As a User, I want a better sign-in flow

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#928]
## User Story
As a User, I want a better sign-in flow so that it is more seamless and with better UX

## Acceptance Criteria
- [ ] Given the sign-in page, I should already see the login options like wallet, mail, google... etc

## Non-functional Criteria (if applicable)
- [ ] Shouldn't take a new user to login or create account more than 2 clicks

## Notes (Optional)
Solved in #975 
- Right now, it take an already registered user to sign-in 3 different modals and changes of view

1
![CleanShot 2024-09-05 at 13 12 51](https://github.com/user-attachments/assets/26ad89c9-142a-4cd1-bb91-91c6de8b28a5)

2
![CleanShot 2024-09-05 at 13 13 01](https://github.com/user-attachments/assets/28e26286-628c-4c31-a284-56a39f44c144)

3
![CleanShot 2024-09-05 at 13 21 12](https://github.com/user-attachments/assets/b110cc30-7050-472a-b010-28f8dfc839e3)

## Mockups & Examples (Optional)
We need to save the first signin click by putting directly the privy modal in the webpage

![image](https://github.com/user-attachments/assets/7beadb51-24eb-46b7-8859-f97e017e59d1)

## Tasks Breakdown (Optional)
- [ ] Thoroughly review privy documentation
- [ ] Save users at least one click for signing in or singing up

**Comment by Mario-SO** [comment]
![image](https://github.com/user-attachments/assets/bc38f52b-7653-4c3e-b9b0-6c2c9012802e)
